services:
  - type: web
    name: as-tool-v1
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    autoDeploy: true
